# Generated by Django 5.2 on 2025-10-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_visionboard_category_remove_visionboard_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='name',
        ),
    ]
