# Generated by Django 5.2 on 2025-10-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_title_board_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='owner',
        ),
    ]
